apiVersion: v1
kind: LimitRange
metadata:
  name: eshop-defaults
  namespace: eshop
spec:
  limits:
    - type: Container
      default:            # limit if not set
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:     # request if not set
        cpu: "50m"
        memory: "64Mi"
      max:                # hard cap per container
        cpu: "1500m"
        memory: "1Gi"
      min:
        cpu: "10m"
        memory: "16Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: eshop-quota
  namespace: eshop
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "8Gi"
    pods: "40"
    services: "30"
    persistentvolumeclaims: "10"